language: go

go:
  - 1.14.x
  - 1.15.x
  - tip

addons:
  apt:
   packages:
    - openjdk-8-jdk-headless

before_install:
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  - java -version
  - sudo rm -rf /var/lib/cassandra/*
  - wget https://archive.apache.org/dist/cassandra/3.0.22/apache-cassandra-3.0.22-bin.tar.gz && tar -xvzf apache-cassandra-3.0.22-bin.tar.gz
  - sudo sh ./apache-cassandra-3.0.22/bin/cassandra -R
  - sleep 20
