language: go

go:
  - 1.11.x
  - 1.12.x
  - tip

addons:
  apt:
   packages:
    - oracle-java8-installer

before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - sudo rm -rf /var/lib/cassandra/*
  - wget https://archive.apache.org/dist/cassandra/3.0.16/apache-cassandra-3.0.16-bin.tar.gz && tar -xvzf apache-cassandra-3.0.16-bin.tar.gz
  - sudo sh ./apache-cassandra-3.0.16/bin/cassandra -R
  - sleep 20
