name: Run Tests
on: 
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x, 1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    services:
      cassandra:
        image: cassandra:3.0.22
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - name: Run Tests
      run: |
        go test -v ./...
